### ISSUE TITLE
CMPNT - Navbar

### ISSUE THREAD

**Issue by lindseysatterfield** [jrobinson0529/taskinator#39]
Create a navbar that allows the user to

- Return to home via the 'Taskinator' in the top left
- Navigate to the admin page
  - Only visible if user is logged in and user IsAdmin!
- Navigate to the Robot Services page which is essentially the categories page
- Log in via a LOGIN button
  - If a user is logged in this button will change to LOGOUT button
- Access their cart via a *cart* icon
  - This icon is hidden if there is no user!
- STRETCH: Search for robots with a keyword via a search icon
  - the search icon may open a search bar when clicked
 - Navigate to users profile page

**Comment by robertncole1** [comment]
![taskinator-logo-transparent-white](https://user-images.githubusercontent.com/76854545/139541065-de118223-26e2-404d-8197-f31e2325c907.png)
